### ISSUE TITLE
read.px error

### ISSUE THREAD

**Issue by Saadi4469** [cjgb/pxR#14]
When ever I run this the code below I get this error:

`Error: C stack usage  17812428 is too close to the limit`

`tbl_census_2018 <- read.px("data/census_2018.px") %>%              # Load & format
  as_tibble()`

How can this be fixed?

**Comment by cjgb** [comment]
First thing... are you using the latest version of the code? I remember having made a number of changes in the past to avoid that kind of problems. 

It could also be that (since you are reading something called "census") that your file is still too big. But let's check the version first.

**Comment by Saadi4469** [comment]
I am using version `1.3.0`, more details about the problem can be found `[here](https://stackoverflow.com/questions/74493020/read-px-c-stack-usage-issue)`.

**Comment by cjgb** [comment]
Can I have a look at the .px file itself? Can you provide a link to it? It could just be it's too large, but I'd be surprised.

**Comment by Saadi4469** [comment]
The data in question can be downloaded from the tutorial link provided in the stackoverflow link provided above.

**Comment by cjgb** [comment]
I uploaded a new version of the code. It is available in Github (cjgb/pxR), and soon in CRAN.

**Comment by Saadi4469** [comment]
What's the code to update the package via `Github`?

**Comment by cjgb** [comment]
You can find an example [here](https://cran.r-project.org/web/packages/githubinstall/vignettes/githubinstall.html).
