### ISSUE TITLE
importance of quotation marks in `na.strings`?

### ISSUE THREAD

**Issue by majazaloznik** [cjgb/pxR#17]
I'm having trouble with one of the Slovenian stat agency's tables, seemingly due to the NA strings. Using the usual setup to read the table produces the following error:
```
id <- "2490201S"
url <- paste0("https://pxweb.stat.si/SiStatData/Resources/PX/Databases/Data/%22, id, ".px")
l <- pxR::read.px(url,  encoding = "CP1250")
Error in scan(tc, na.strings = na.strings, quote = NULL, quiet = TRUE) : 
  scan() expected 'a real', got '....'
```
If I manually add `'....'`, it works fine:
```
l <- pxR::read.px(url, encoding = "CP1250",
                  na.strings = c('"."', '".."', '"..."', '"...."', '....')
)
```
Without checking other tables to see if they use dot notation in any other way, this seems odd, that the quotation in the default `na.strings` argument seems to not apply in this case. Any ideas? Should I just add the ., .., and ... without quotes as well to future-proof the code?

**Comment by cjgb** [comment]
There is nothing 100% sure in the px data standard. The default seemed to cover most cases known to the developers at the time, but users (Slovenian stat agency, for example) could use almost anything to indicate NAs.
